development:
  adapter: redis
  url:  <%= ENV.fetch("REDIS_URL") { "redis://redis:6379/0" } %>

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://127.0.0.1:6379" } %>
  channel_prefix: proscripe_production
